Started logging messages at Thu Aug 20 20:55:08 2020
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 18 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 61
Info:            Created 
Info:        Working on 83
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 81
Info:            Created 
Info:        Working on 107
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 106
Info:            Created 
Info:        Working on 134
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 133
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 29
Info:            Created 
Info:        Working on 163
Info:            Created 
Info:        Working on 207
Info:            Created 
Info:        Working on 44
Info:            Created 
Info:        Working on 206
Info:            Created 
Info:        Working on 268
Info:            Created 
Info:        Working on 65
Info:            Created 
Info:        Working on 267
Info:            Created 
Info:        Working on 323
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 322
Info:            Created 
Info:        Working on 351
Info:            Created 
Info:        Working on 117
Info:            Created 
Info:        Working on 350
Info:            Created 
Info:        Working on 361
Info:            Created 
Info:        Working on 147
Info:            Created 
Info:        Working on 356
Info:            Created 
Info:        Working on 362
Info:            Created 
Info:        Working on 190
Info:            Created 
Info:        Working on 336
Info:            Created 
Info:        Working on 355
Info:            Created 
Info:        Working on 251
Info:            Created 
Info:        Working on 291
Info:            Created 
Info:        Working on 328
Info:            Created 
Info:        Working on 310
Info:            Created 
Info:        Working on 331
Info:            Created 
Info:        Working on 285
Info:            Created 
Info:        Working on 246
Info:            Created 
Info:        Working on 302
Info:            Created 
Info:        Working on 345
Info:            Created 
Info:        Working on 332
Info:            Created 
Info:        Working on 299
Info:            Created 
Info:        Working on 358
Info:            Created 
Info:        Working on 286
Info:            Created 
Info:        Working on 247
Info:            Created 
Info:        Working on 341
Info:            Created 
Info:        Working on 308
Info:            Created 
Info:        Working on 86
Info:            Created 
Info:        Working on 110
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 0.000105802
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Thu Aug 20 20:55:08 2020
